[[character]]
key = "phos"
character="Phosphophyllite"
nickname="none"
quote = "You mustn't run away."
source = "Houseki No Kuni"
image_path = "assets/phos.jfif"

[[character]]
key = "klein_moretti"
character="Klein Moretti"
nickname="""
The Best Elder Brother, The Best younger Brother, The Best Colleague, Zhou Mingrou, Klein Moretti, Sherlock Moriaty, Gerhman Sparrow, Dwayne Dantes,
Merlin Hermes, The Fool,  Angel who Redeems Mankind, Sea God, Craziest Hunter, Strongest Adventurer of the Five Seas, Angel of Redemption, Half-Lord of MysteriesKing of Space-Time,
"""
quote = """A person who’s very sentimental;
A person from Earth, but to a certain extent, a person who has been reconstructed into a new person because of the fusion with Klein Moretti’s memory fragments;
A person who didn’t spend too much time with the Nighthawks but has had that period of time deeply influence his actions and choices;
A person who tries to play safe and is afraid of danger but is able to change his mind at the critical moment;
A person who truly wants to skive, eat delicious food, travel, and enjoy life, but he has no choice but to be busy with more important matters;
A person who likes beautiful women, but he doesn’t give himself up to pleasure to keep to his principles;
A person who loves money but is willing to spend large sums of money for his siblings;
A person who hides his pain inside while showing a smile to others;
A person who’s used to lampooning inwardly but appears gentlemanly on the surface;
A person who can overcome his psychological traumas but never crosses his bottom line;
A person who feels embarrassed for his acting;
He’s also a guardian, a miserable wretch that is constantly fighting against threats and madness!"
source = "Lord of the Mysteries"
image_path = "assets/phos.jfif"""
